DROP DATABASE IF EXISTS recruiting_db;
CREATE DATABASE recruiting_db;
USE recruiting_db;

CREATE TABLE utenti(
    id INT (5) UNSIGNED ZEROFILL NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(20) NOT NULL,
    cognome VARCHAR(20) NOT NULL,
    username VARCHAR(32) NOT NULL UNIQUE,
    email VARCHAR(30) NOT NULL UNIQUE,
    password CHAR(64) NOT NULL,
    salt CHAR(64) NOT NULL,

    tipoAccount ENUM('Candidati', 'Azienda') NOT NULL DEFAULT 'Candidati'
);

CREATE TABLE Candidati (
    codF VARCHAR(16) NOT NULL PRIMARY KEY,
    link_CV VARCHAR(50) NOT NULL,
	dataNascita DATE NOT NULL,
	genere ENUM ("m","f"),
    esperienze TEXT,
	numeroTelefono VARCHAR(11) NULL,
	FkidUtenti INT (5) UNSIGNED ZEROFILL NOT NULL,
	FOREIGN KEY(FkidUtenti) REFERENCES utenti(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE

);

CREATE TABLE Candidature (
    stato ENUM ("inviata","in_revisione","colloquio","accettata") DEFAULT "inviata",
	codCand INT(2) UNSIGNED ZEROFILL PRIMARY KEY NOT NULL AUTO_INCREMENT,
    codAnl INT(5) UNSIGNED ZEROFILL NOT NULL,
    dataCandidatura TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	FKcodF VARCHAR(16) NOT NULL,
    FOREIGN KEY (FKcodF) REFERENCES Candidati(codF)
        ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE Categorie_Competenze (
    codCat INT(2) UNSIGNED ZEROFILL PRIMARY KEY AUTO_INCREMENT,
    nomeCat VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE Competenze (
    codCr INT(2) UNSIGNED ZEROFILL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(20) NOT NULL,
    FKcodCat INT(2) UNSIGNED ZEROFILL NOT NULL,
    FOREIGN KEY (FKcodCat) REFERENCES Categorie_Competenze(codCat)
        ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE Aziende (
    codA INT(2) UNSIGNED ZEROFILL NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nomeAzienda VARCHAR (25) NOT NULL,
	ragioneSociale VARCHAR(30) NOT NULL,
    ind_via VARCHAR(20) NOT NULL,
    ind_civ VARCHAR(15) NOT NULL,
    ind_citta VARCHAR(20) NOT NULL,
	cap VARCHAR (5) NOT NULL,
	FkidUtenti INT(5) UNSIGNED ZEROFILL NOT NULL,
	FOREIGN KEY(FkidUtenti) REFERENCES utenti(id)
	ON DELETE CASCADE
	ON UPDATE CASCADE

);

CREATE TABLE Settori (
    codSett INT(2) UNSIGNED ZEROFILL PRIMARY KEY AUTO_INCREMENT,
    nomeSettore VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE Contratti (
    codC INT(3) UNSIGNED ZEROFILL PRIMARY KEY AUTO_INCREMENT,
    gFerie INT(2) UNSIGNED,
    nOre_settimanali INT(2) UNSIGNED ZEROFILL,
    nomeContratto VARCHAR(20) NOT NULL
);

CREATE TABLE Annunci_lavoro (
    codAnl INT(5) PRIMARY KEY,
    titolo VARCHAR (30) NOT NULL,
    requisiti TEXT,
    descrizione TEXT,
	durataContrattoGiorni INT(3),
    Ral int(6) UNSIGNED NOT NULL,
	FKcodA INT(2) UNSIGNED ZEROFILL NOT NULL,
    FKcodSett INT(2) UNSIGNED ZEROFILL NOT NULL,
    FKcodC INT(3) UNSIGNED ZEROFILL NOT NULL,
    FOREIGN KEY (FKcodA) REFERENCES Aziende(codA)
	    ON DELETE CASCADE
		ON UPDATE CASCADE,
    FOREIGN KEY (FKcodSett) REFERENCES Settori(codSett)
	    ON DELETE CASCADE
		ON UPDATE CASCADE,
    FOREIGN KEY (FKcodC) REFERENCES Contratti(codC)
	    ON DELETE RESTRICT
		ON UPDATE CASCADE 
);

CREATE TABLE Colloqui (
    codQ INT(2) UNSIGNED ZEROFILL PRIMARY KEY AUTO_INCREMENT,
    FKcodCand INT(2) UNSIGNED ZEROFILL NOT NULL,
    esito BOOLEAN,
	dataColloquio DATETIME,
    FOREIGN KEY (FKcodCand) REFERENCES Candidature(codCand)
        ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE Messaggio (
    codM INT(2) UNSIGNED ZEROFILL NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FKcodQ INT(2) UNSIGNED ZEROFILL NOT NULL,
    contenuto TEXT NOT NULL,
    dataOra_invio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    utente BOOLEAN NOT NULL,
    FOREIGN KEY (FKcodQ) REFERENCES Colloqui(codQ)
        ON DELETE CASCADE
		ON UPDATE CASCADE
);

